services:
  - type: web
    name: motherday-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    plan: free
    region: oregon
    branch: main
    repo: https://github.com/PechNik3/motherday
